package update

import (
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"time"
)

// GitHub credentials stay on this machine. They are sent only to the API host;
// signed asset redirects must not receive the token.
func githubToken(ctx context.Context) string {
	token, configured := os.LookupEnv("READYRIG_UPDATE_TOKEN")
	if !configured {
		token = os.Getenv("RELAY_UPDATE_TOKEN")
	}
	if token != "" {
		return token
	}
	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	for _, path := range []string{"gh", "/opt/homebrew/bin/gh", "/usr/local/bin/gh"} {
		b, err := exec.CommandContext(ctx, path, "auth", "token", "--hostname", "github.com").Output()
		if err == nil {
			return strings.TrimSpace(string(b))
		}
	}
	return ""
}

func (u *Manager) authorize(req *http.Request) {
	if req.URL.Scheme != "https" || req.URL.Host != "api.github.com" {
		return
	}
	u.tokenOnce.Do(func() { u.token = githubToken(req.Context()) })
	if u.token != "" {
		req.Header.Set("Authorization", "Bearer "+u.token)
	}
	if strings.Contains(req.URL.Path, "/releases/assets/") {
		req.Header.Set("Accept", "application/octet-stream")
	} else {
		req.Header.Set("Accept", "application/vnd.github+json")
	}
	req.Header.Set("X-GitHub-Api-Version", "2022-11-28")
}

var repoPattern = regexp.MustCompile(`^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$`)

func GitHubFeed(repo string) (string, error) {
	repo = strings.TrimSuffix(strings.TrimPrefix(strings.TrimSpace(repo), "https://github.com/"), "/")
	if !repoPattern.MatchString(repo) {
		return "", errors.New("release repository must be owner/repo or a GitHub repository URL")
	}
	return "https://api.github.com/repos/" + repo + "/releases/latest", nil
}

func (u *Manager) decodeRelease(ctx context.Context, b []byte) (*Release, error) {
	var shape struct {
		Tag string `json:"tag_name"`
	}
	if err := json.Unmarshal(b, &shape); err != nil {
		return nil, err
	}
	if shape.Tag == "" {
		var rel Release
		err := json.Unmarshal(b, &rel)
		return &rel, err
	}
	var gh struct {
		Tag    string `json:"tag_name"`
		Notes  string `json:"body"`
		URL    string `json:"html_url"`
		Draft  bool   `json:"draft"`
		Assets []struct {
			Name   string `json:"name"`
			URL    string `json:"browser_download_url"`
			APIURL string `json:"url"`
			Size   int64  `json:"size"`
			Digest string `json:"digest"`
		} `json:"assets"`
	}
	if err := json.Unmarshal(b, &gh); err != nil {
		return nil, err
	}
	if gh.Draft {
		return nil, errors.New("cannot install a draft release")
	}
	r := &Release{Version: strings.TrimPrefix(gh.Tag, "v"), Notes: gh.Notes, URL: gh.URL, Assets: map[string]Asset{}}
	checksums := ""
	for _, a := range gh.Assets {
		if a.APIURL != "" {
			a.URL = a.APIURL
		}
		if a.Name == "SHA256SUMS" {
			checksums = a.URL
		}
		digest, _ := strings.CutPrefix(a.Digest, "sha256:")
		r.Assets[a.Name] = Asset{URL: a.URL, Size: a.Size, SHA256: digest}
	}
	// Current GitHub uploads include a digest; older releases can supply the
	// conventional SHA256SUMS generated by our release script.
	if name, a, ok := u.releaseAsset(r); ok && a.SHA256 == "" && checksums != "" {
		res, err := u.get(ctx, checksums)
		if err != nil {
			return nil, err
		}
		defer res.Body.Close()
		body, err := io.ReadAll(io.LimitReader(res.Body, (1<<20)+1))
		if err != nil {
			return nil, err
		}
		if len(body) > 1<<20 {
			return nil, errors.New("checksums exceed 1 MiB")
		}
		for _, line := range strings.Split(string(body), "\n") {
			parts := strings.Fields(line)
			if len(parts) == 2 && strings.TrimPrefix(parts[1], "*") == name {
				a.SHA256 = parts[0]
				r.Assets[name] = a
				break
			}
		}
	}
	return r, nil
}
