import type { Locale } from '../locale.ts'

// Translations for the intro film. The film's markup in stage.html is written in English, so English is the source
// and every other locale is listed here; the type forces each entry to cover all of them. Text that is not listed
// (file names, tool names, commands, numbers, times) is the same in every language and stays as it is.
type Entry = Record<Exclude<Locale, 'en'>, string>

const e = (zhCN: string, zhTW: string, ja: string, ko: string, es: string, fr: string, de: string): Entry => ({
  'zh-CN': zhCN,
  'zh-TW': zhTW,
  ja,
  ko,
  es,
  fr,
  de,
})

export const filmStrings: Readonly<Record<string, Entry>> = {
  // Menu bar and chapters
  File: e('文件', '檔案', 'ファイル', '파일', 'Archivo', 'Fichier', 'Datei'),
  Edit: e('编辑', '編輯', '編集', '편집', 'Edición', 'Édition', 'Bearbeiten'),
  View: e('显示', '顯示', '表示', '보기', 'Visualización', 'Présentation', 'Darstellung'),
  Special: e('特别', '特別', '特別', '특별', 'Especial', 'Spécial', 'Spezial'),
  Boot: e('启动', '啟動', '起動', '부팅', 'Inicio', 'Démarrage', 'Start'),
  'The wall': e('隔阂', '隔閡', '壁', '벽', 'El muro', 'Le mur', 'Die Wand'),
  Connect: e('连接', '連接', '接続', '연결', 'Conectar', 'Connexion', 'Verbinden'),
  Work: e('工作', '工作', '作業', '작업', 'Trabajo', 'Travail', 'Arbeit'),
  Screen: e('屏幕', '螢幕', '画面', '화면', 'Pantalla', 'Écran', 'Bildschirm'),
  Logs: e('日志', '日誌', 'ログ', '로그', 'Registros', 'Journaux', 'Protokolle'),
  Console: e('控制台', '主控台', 'コンソール', '콘솔', 'Consola', 'Console', 'Konsole'),
  Activity: e('活动', '活動', 'アクティビティ', '활동', 'Actividad', 'Activité', 'Aktivität'),
  Control: e('控制', '控制', '制御', '제어', 'Control', 'Contrôle', 'Steuerung'),
  'Get started': e('开始使用', '開始使用', 'はじめる', '시작하기', 'Empezar', 'Commencer', 'Los geht’s'),

  // Boot and the wall
  'Your computer, ready for any agent.': e(
    '你的电脑，随时为任何 Agent 就绪。',
    '你的電腦，隨時為任何 Agent 就緒。',
    'あなたのコンピュータを、あらゆるエージェントのために。',
    '당신의 컴퓨터를 모든 에이전트에게 열어 두세요.',
    'Tu ordenador, listo para cualquier agente.',
    'Votre ordinateur, prêt pour n’importe quel agent.',
    'Dein Computer, bereit für jeden Agenten.',
  ),
  'Remote Agent': e('远程 Agent', '遠端 Agent', 'リモートエージェント', '원격 에이전트', 'Agente remoto', 'Agent distant', 'Remote-Agent'),
  'In the cloud': e('在云端', '在雲端', 'クラウド上', '클라우드에서', 'En la nube', 'Dans le cloud', 'In der Cloud'),
  'Plans the task': e('规划任务', '規劃任務', 'タスクを計画', '작업 계획', 'Planifica la tarea', 'Planifie la tâche', 'Plant die Aufgabe'),
  'Writes the code': e('编写代码', '撰寫程式碼', 'コードを書く', '코드 작성', 'Escribe el código', 'Écrit le code', 'Schreibt den Code'),
  'Reasons it through': e('推理分析', '推理分析', '推論する', '추론', 'Razona el problema', 'Raisonne', 'Denkt es durch'),
  'Your Computer': e('你的电脑', '你的電腦', 'あなたのコンピュータ', '내 컴퓨터', 'Tu ordenador', 'Votre ordinateur', 'Dein Computer'),
  Files: e('文件', '檔案', 'ファイル', '파일', 'Archivos', 'Fichiers', 'Dateien'),
  'out of reach': e('无法访问', '無法存取', 'アクセス不可', '접근 불가', 'fuera de alcance', 'hors de portée', 'außer Reichweite'),
  Terminal: e('终端', '終端機', 'ターミナル', '터미널', 'Terminal', 'Terminal', 'Terminal'),
  'Browser · Desktop': e('浏览器 · 桌面', '瀏覽器 · 桌面', 'ブラウザ · デスクトップ', '브라우저 · 데스크톱', 'Navegador · Escritorio', 'Navigateur · Bureau', 'Browser · Desktop'),
  'Can’t reach “Your Computer”.': e(
    '无法连接“你的电脑”。',
    '無法連接「你的電腦」。',
    '「あなたのコンピュータ」に接続できません。',
    '“내 컴퓨터”에 연결할 수 없습니다.',
    'No se puede acceder a «Tu ordenador».',
    'Impossible d’accéder à « Votre ordinateur ».',
    '„Dein Computer“ ist nicht erreichbar.',
  ),
  'The agent has no hands on this computer.': e(
    'Agent 无法操作这台电脑。',
    'Agent 無法操作這台電腦。',
    'エージェントはこのコンピュータを操作できません。',
    '에이전트는 이 컴퓨터를 조작할 수 없습니다.',
    'El agente no tiene manos en este ordenador.',
    'L’agent n’a pas la main sur cet ordinateur.',
    'Der Agent hat keinen Zugriff auf diesen Computer.',
  ),
  Cancel: e('取消', '取消', 'キャンセル', '취소', 'Cancelar', 'Annuler', 'Abbrechen'),
  '✓ Connected': e('✓ 已连接', '✓ 已連接', '✓ 接続済み', '✓ 연결됨', '✓ Conectado', '✓ Connecté', '✓ Verbunden'),
  'Agents can plan and write code, but your computer is out of reach.': e(
    'Agent 能规划、写代码，却够不到你的电脑。',
    'Agent 能規劃、寫程式，卻碰不到你的電腦。',
    'エージェントは計画もコード作成もできますが、あなたのコンピュータには手が届きません。',
    '에이전트는 계획하고 코드를 쓸 수 있지만, 당신의 컴퓨터에는 닿지 못합니다.',
    'Los agentes pueden planificar y escribir código, pero tu ordenador queda fuera de su alcance.',
    'Les agents savent planifier et écrire du code, mais votre ordinateur reste hors de portée.',
    'Agenten können planen und Code schreiben – dein Computer bleibt jedoch außer Reichweite.',
  ),
  'ReadyRig is the bridge.': e('ReadyRig 就是那座桥。', 'ReadyRig 就是那座橋。', 'ReadyRig がその橋渡しです。', 'ReadyRig가 그 다리가 됩니다.', 'ReadyRig es el puente.', 'ReadyRig est le pont.', 'ReadyRig ist die Brücke.'),

  // Connect
  'Remote agent': e('远程 Agent', '遠端 Agent', 'リモートエージェント', '원격 에이전트', 'Agente remoto', 'Agent distant', 'Remote-Agent'),
  'Revocable access': e('可撤销的访问', '可撤銷的存取', '取り消し可能なアクセス', '철회 가능한 액세스', 'Acceso revocable', 'Accès révocable', 'Widerrufbarer Zugriff'),
  Capabilities: e('能力', '功能', '機能', '기능', 'Capacidades', 'Capacités', 'Funktionen'),
  Desktop: e('桌面', '桌面', 'デスクトップ', '데스크톱', 'Escritorio', 'Bureau', 'Desktop'),
  'Public sharing:': e('公网分享：', '公開分享：', '公開共有：', '공개 공유:', 'Compartir públicamente:', 'Partage public :', 'Öffentliches Teilen:'),
  ready: e('就绪', '就緒', '準備完了', '준비됨', 'listo', 'prêt', 'bereit'),
  'temporary link': e('临时链接', '臨時連結', '一時リンク', '임시 링크', 'enlace temporal', 'lien temporaire', 'temporärer Link'),
  'Console · Connection · real screenshot': e(
    '控制台 · 连接 · 真实截图',
    '主控台 · 連接 · 真實截圖',
    'コンソール · 接続 · 実際のスクリーンショット',
    '콘솔 · 연결 · 실제 스크린샷',
    'Consola · Conexión · captura real',
    'Console · Connexion · capture réelle',
    'Konsole · Verbindung · echter Screenshot',
  ),
  'One link in. You switch on only the tools you want.': e(
    '一条链接接入，只开启你想要的工具。',
    '一條連結接入，只開啟你想要的工具。',
    'リンクを1つ渡すだけ。必要なツールだけをオンにします。',
    '링크 하나로 연결하고, 원하는 도구만 켭니다.',
    'Un solo enlace. Activas solo las herramientas que quieras.',
    'Un seul lien. Vous n’activez que les outils voulus.',
    'Ein Link genügt. Du aktivierst nur die gewünschten Tools.',
  ),

  // Work
  'Agent chat': e('Agent 对话', 'Agent 對話', 'エージェントチャット', '에이전트 채팅', 'Chat del agente', 'Discussion avec l’agent', 'Agent-Chat'),
  'Read the README and run the tests.': e(
    '读一下 README，然后运行测试。',
    '讀一下 README，然後執行測試。',
    'README を読んで、テストを実行して。',
    'README를 읽고 테스트를 실행해 줘.',
    'Lee el README y ejecuta las pruebas.',
    'Lis le README et lance les tests.',
    'Lies die README und führe die Tests aus.',
  ),
  "On it. I'll use ReadyRig on your computer.": e(
    '好的，我通过 ReadyRig 在你的电脑上操作。',
    '好的，我透過 ReadyRig 在你的電腦上操作。',
    '了解です。ReadyRig であなたのコンピュータを使います。',
    '알겠어요. ReadyRig로 당신의 컴퓨터를 사용할게요.',
    'Entendido. Usaré ReadyRig en tu ordenador.',
    'Je m’en occupe. J’utilise ReadyRig sur votre ordinateur.',
    'Mache ich. Ich nutze ReadyRig auf deinem Computer.',
  ),
  'Done. The tests pass and the README covers install, CLI, security and the console.': e(
    '完成。测试通过，README 涵盖安装、CLI、安全与控制台。',
    '完成。測試通過，README 涵蓋安裝、CLI、安全與主控台。',
    '完了しました。テストは成功し、README にはインストール、CLI、セキュリティ、コンソールが載っています。',
    '완료했어요. 테스트가 통과했고 README는 설치, CLI, 보안, 콘솔을 다룹니다.',
    'Hecho. Las pruebas pasan y el README cubre instalación, CLI, seguridad y consola.',
    'Terminé. Les tests passent et le README couvre l’installation, la CLI, la sécurité et la console.',
    'Fertig. Die Tests bestehen, und die README behandelt Installation, CLI, Sicherheit und Konsole.',
  ),
  'Tool calls': e('工具调用', '工具呼叫', 'ツール呼び出し', '도구 호출', 'Llamadas a herramientas', 'Appels d’outils', 'Tool-Aufrufe'),
  'Ask in plain words. The agent reads files and runs commands through ReadyRig.': e(
    '用平常的话提问。Agent 通过 ReadyRig 读取文件、运行命令。',
    '用平常的話提問。Agent 透過 ReadyRig 讀取檔案、執行指令。',
    'ふつうの言葉で頼むだけ。エージェントが ReadyRig 経由でファイルを読み、コマンドを実行します。',
    '평소 말투로 요청하세요. 에이전트가 ReadyRig로 파일을 읽고 명령을 실행합니다.',
    'Pide con tus palabras. El agente lee archivos y ejecuta comandos con ReadyRig.',
    'Demandez simplement. L’agent lit des fichiers et lance des commandes via ReadyRig.',
    'Frag einfach drauflos. Der Agent liest Dateien und führt Befehle über ReadyRig aus.',
  ),

  // Screen
  'Chrome · readyrig.getmegaportal.com · real screenshot': e(
    'Chrome · readyrig.getmegaportal.com · 真实截图',
    'Chrome · readyrig.getmegaportal.com · 真實截圖',
    'Chrome · readyrig.getmegaportal.com · 実際のスクリーンショット',
    'Chrome · readyrig.getmegaportal.com · 실제 스크린샷',
    'Chrome · readyrig.getmegaportal.com · captura real',
    'Chrome · readyrig.getmegaportal.com · capture réelle',
    'Chrome · readyrig.getmegaportal.com · echter Screenshot',
  ),
  'Desktop replay': e('桌面回放', '桌面重播', 'デスクトップの再生', '데스크톱 리플레이', 'Reproducción del escritorio', 'Relecture du bureau', 'Desktop-Wiedergabe'),
  'frame by frame': e('逐帧', '逐格', 'コマ送り', '프레임 단위', 'fotograma a fotograma', 'image par image', 'Bild für Bild'),
  Permissions: e('权限', '權限', '権限', '권한', 'Permisos', 'Autorisations', 'Berechtigungen'),
  'Screen Recording': e('屏幕录制', '螢幕錄製', '画面収録', '화면 기록', 'Grabación de pantalla', 'Enregistrement de l’écran', 'Bildschirmaufnahme'),
  Accessibility: e('辅助功能', '輔助使用', 'アクセシビリティ', '손쉬운 사용', 'Accesibilidad', 'Accessibilité', 'Bedienungshilfen'),
  'It can see the screen and click, once macOS permission is granted.': e(
    '获得 macOS 授权后，它就能看到屏幕并点击。',
    '取得 macOS 授權後，它就能看到螢幕並點擊。',
    'macOS の許可が与えられると、画面を見てクリックできます。',
    'macOS 권한을 허용하면 화면을 보고 클릭할 수 있습니다.',
    'Con el permiso de macOS, puede ver la pantalla y hacer clic.',
    'Une fois l’autorisation macOS accordée, il voit l’écran et peut cliquer.',
    'Mit der macOS-Freigabe kann er den Bildschirm sehen und klicken.',
  ),

  // Logs
  'Activity summary': e('活动概览', '活動概覽', 'アクティビティの概要', '활동 요약', 'Resumen de actividad', 'Résumé de l’activité', 'Aktivitätsübersicht'),
  'Example activity log': e('活动日志示例', '活動日誌範例', 'アクティビティログの例', '활동 로그 예시', 'Registro de actividad de ejemplo', 'Exemple de journal d’activité', 'Beispiel-Aktivitätsprotokoll'),
  'tool calls': e('次工具调用', '次工具呼叫', 'ツール呼び出し', '도구 호출', 'llamadas a herramientas', 'appels d’outils', 'Tool-Aufrufe'),
  succeeded: e('成功', '成功', '成功', '성공', 'correctas', 'réussis', 'erfolgreich'),
  sessions: e('会话', '工作階段', 'セッション', '세션', 'sesiones', 'sessions', 'Sitzungen'),
  clients: e('客户端', '用戶端', 'クライアント', '클라이언트', 'clientes', 'clients', 'Clients'),
  '4 errors and 1 running call. Nothing is hidden.': e(
    '4 个错误、1 个进行中的调用，毫无隐瞒。',
    '4 個錯誤、1 個進行中的呼叫，毫無隱瞞。',
    'エラー4件、実行中1件。隠しごとはありません。',
    '오류 4건, 실행 중 1건. 숨기는 것은 없습니다.',
    '4 errores y 1 llamada en curso. Nada se oculta.',
    '4 erreurs et 1 appel en cours. Rien n’est caché.',
    '4 Fehler und 1 laufender Aufruf. Nichts bleibt verborgen.',
  ),
  'Calls by tool': e('按工具统计调用', '依工具統計呼叫', 'ツール別の呼び出し', '도구별 호출', 'Llamadas por herramienta', 'Appels par outil', 'Aufrufe pro Tool'),
  'Calls per day': e('每日调用', '每日呼叫', '日別の呼び出し', '일별 호출', 'Llamadas por día', 'Appels par jour', 'Aufrufe pro Tag'),
  'Sep 30': e('9月30日', '9月30日', '9月30日', '9월 30일', '30 sep', '30 sept.', '30. Sep'),
  'Oct 1': e('10月1日', '10月1日', '10月1日', '10월 1일', '1 oct', '1 oct.', '1. Okt'),
  'Oct 2': e('10月2日', '10月2日', '10月2日', '10월 2일', '2 oct', '2 oct.', '2. Okt'),
  'solid: local tools': e('实心：本地工具', '實心：本機工具', '塗りつぶし：ローカルツール', '채움: 로컬 도구', 'sólido: herramientas locales', 'plein : outils locaux', 'gefüllt: lokale Tools'),
  'hatched: Chrome tools': e('斜纹：Chrome 工具', '斜紋：Chrome 工具', '斜線：Chrome ツール', '빗금: Chrome 도구', 'rayado: herramientas de Chrome', 'hachuré : outils Chrome', 'schraffiert: Chrome-Tools'),
  'Everything is logged on your machine, in a local database.': e(
    '一切都记录在你电脑的本地数据库中。',
    '一切都記錄在你電腦的本機資料庫中。',
    'すべてあなたのマシン上のローカルデータベースに記録されます。',
    '모든 기록은 당신의 컴퓨터의 로컬 데이터베이스에 저장됩니다.',
    'Todo queda registrado en tu equipo, en una base de datos local.',
    'Tout est consigné sur votre machine, dans une base de données locale.',
    'Alles wird auf deinem Rechner in einer lokalen Datenbank protokolliert.',
  ),

  // Console
  'ReadyRig console · Activity · real screenshot': e(
    'ReadyRig 控制台 · 活动 · 真实截图',
    'ReadyRig 主控台 · 活動 · 真實截圖',
    'ReadyRig コンソール · アクティビティ · 実際のスクリーンショット',
    'ReadyRig 콘솔 · 활동 · 실제 스크린샷',
    'Consola de ReadyRig · Actividad · captura real',
    'Console ReadyRig · Activité · capture réelle',
    'ReadyRig-Konsole · Aktivität · echter Screenshot',
  ),
  'The console': e('控制台', '主控台', 'コンソール', '콘솔', 'La consola', 'La console', 'Die Konsole'),
  'Calls, running, time': e('调用、进行中、耗时', '呼叫、進行中、耗時', '呼び出し・実行中・所要時間', '호출, 실행 중, 소요 시간', 'Llamadas, en curso, tiempo', 'Appels, en cours, durée', 'Aufrufe, laufend, Zeit'),
  'Filter by tool kind': e('按工具类型筛选', '依工具類型篩選', 'ツールの種類で絞り込み', '도구 종류별 필터', 'Filtrar por tipo de herramienta', 'Filtrer par type d’outil', 'Nach Tool-Art filtern'),
  'Search args and errors': e('搜索参数与错误', '搜尋參數與錯誤', '引数とエラーを検索', '인자와 오류 검색', 'Buscar argumentos y errores', 'Rechercher arguments et erreurs', 'Argumente und Fehler durchsuchen'),
  'Pause in one click': e('一键暂停', '一鍵暫停', 'ワンクリックで一時停止', '한 번에 일시중지', 'Pausa con un clic', 'Pause en un clic', 'Pause mit einem Klick'),
  'Export as NDJSON': e('导出为 NDJSON', '匯出為 NDJSON', 'NDJSON で書き出し', 'NDJSON으로 내보내기', 'Exportar como NDJSON', 'Exporter en NDJSON', 'Als NDJSON exportieren'),
  'The desktop app and a browser console show every call as it happens.': e(
    '桌面 App 和浏览器控制台实时显示每一次调用。',
    '桌面 App 與瀏覽器主控台即時顯示每一次呼叫。',
    'デスクトップアプリとブラウザのコンソールが、すべての呼び出しをリアルタイムで表示します。',
    '데스크톱 앱과 브라우저 콘솔이 모든 호출을 실시간으로 보여줍니다.',
    'La app de escritorio y la consola del navegador muestran cada llamada en tiempo real.',
    'L’app de bureau et la console du navigateur affichent chaque appel en direct.',
    'Die Desktop-App und die Browser-Konsole zeigen jeden Aufruf in Echtzeit.',
  ),

  // Activity
  'Activity · example log · times in UTC': e(
    '活动 · 示例日志 · 时间为 UTC',
    '活動 · 範例日誌 · 時間為 UTC',
    'アクティビティ · ログの例 · 時刻は UTC',
    '활동 · 예시 로그 · 시간은 UTC',
    'Actividad · registro de ejemplo · horas en UTC',
    'Activité · exemple de journal · heures en UTC',
    'Aktivität · Beispielprotokoll · Zeiten in UTC',
  ),
  Time: e('时间', '時間', '時刻', '시간', 'Hora', 'Heure', 'Zeit'),
  Tool: e('工具', '工具', 'ツール', '도구', 'Herramienta', 'Outil', 'Tool'),
  Client: e('客户端', '用戶端', 'クライアント', '클라이언트', 'Cliente', 'Client', 'Client'),
  Took: e('耗时', '耗時', '所要時間', '소요', 'Duración', 'Durée', 'Dauer'),
  Result: e('结果', '結果', '結果', '결과', 'Resultado', 'Résultat', 'Ergebnis'),
  '◔ running': e('◔ 进行中', '◔ 進行中', '◔ 実行中', '◔ 실행 중', '◔ en curso', '◔ en cours', '◔ läuft'),
  '✓ success': e('✓ 成功', '✓ 成功', '✓ 成功', '✓ 성공', '✓ correcto', '✓ succès', '✓ Erfolg'),
  '✕ error': e('✕ 错误', '✕ 錯誤', '✕ エラー', '✕ 오류', '✕ error', '✕ erreur', '✕ Fehler'),
  'The failed call stays in the list. Check it before you retry.': e(
    '失败的调用会留在列表里。重试前先看一眼。',
    '失敗的呼叫會留在列表中。重試前先看一眼。',
    '失敗した呼び出しもリストに残ります。再試行する前に確認しましょう。',
    '실패한 호출도 목록에 남습니다. 재시도하기 전에 확인하세요.',
    'La llamada fallida permanece en la lista. Revísala antes de reintentar.',
    'L’appel échoué reste dans la liste. Vérifiez-le avant de réessayer.',
    'Der fehlgeschlagene Aufruf bleibt in der Liste. Prüfe ihn vor einem neuen Versuch.',
  ),
  'Every call is listed with its tool, time and result.': e(
    '每次调用都列出工具、时间和结果。',
    '每次呼叫都列出工具、時間與結果。',
    'すべての呼び出しが、ツール・時刻・結果とともに並びます。',
    '모든 호출이 도구, 시간, 결과와 함께 나열됩니다.',
    'Cada llamada aparece con su herramienta, hora y resultado.',
    'Chaque appel est listé avec son outil, son heure et son résultat.',
    'Jeder Aufruf wird mit Tool, Zeit und Ergebnis aufgelistet.',
  ),

  // Control
  'Control panel': e('控制面板', '控制面板', 'コントロールパネル', '제어판', 'Panel de control', 'Panneau de contrôle', 'Bedienfeld'),
  'approved folders only': e('仅限已批准的文件夹', '僅限已核准的資料夾', '承認済みフォルダのみ', '승인된 폴더만', 'solo carpetas aprobadas', 'dossiers approuvés uniquement', 'nur freigegebene Ordner'),
  'off until you say so': e('你开启前保持关闭', '你開啟前保持關閉', 'あなたがオンにするまでオフ', '직접 켜기 전까지 꺼짐', 'desactivado hasta que lo indiques', 'désactivé tant que vous ne l’autorisez pas', 'aus, bis du es erlaubst'),
  'needs macOS permission': e('需要 macOS 授权', '需要 macOS 授權', 'macOS の許可が必要', 'macOS 권한 필요', 'requiere permiso de macOS', 'nécessite l’autorisation macOS', 'benötigt macOS-Freigabe'),
  'Full Access': e('完全访问', '完整存取', 'フルアクセス', '전체 접근', 'Acceso total', 'Accès complet', 'Vollzugriff'),
  'per session only': e('仅限本次会话', '僅限本次工作階段', 'このセッションのみ', '세션 동안만', 'solo por sesión', 'par session uniquement', 'nur pro Sitzung'),
  'Log, secrets redacted': e('日志，密钥已隐去', '日誌，密鑰已隱去', 'ログ（秘密情報は伏せ字）', '로그, 비밀 정보 가림', 'Registro, secretos ocultos', 'Journal, secrets masqués', 'Protokoll, Geheimnisse geschwärzt'),
  'stays on your computer': e('留在你的电脑上', '留在你的電腦上', 'あなたのコンピュータに残ります', '당신의 컴퓨터에 남습니다', 'se queda en tu ordenador', 'reste sur votre ordinateur', 'bleibt auf deinem Computer'),
  Pause: e('暂停', '暫停', '一時停止', '일시중지', 'Pausa', 'Pause', 'Pause'),
  'Paused.': e('已暂停。', '已暫停。', '一時停止中。', '일시중지됨.', 'En pausa.', 'En pause.', 'Pausiert.'),
  'New tool calls are blocked. Help still works.': e(
    '新的工具调用已被阻止，help 仍可使用。',
    '新的工具呼叫已被阻擋，help 仍可使用。',
    '新しいツール呼び出しはブロックされます。help は引き続き使えます。',
    '새 도구 호출은 차단됩니다. help는 계속 작동합니다.',
    'Se bloquean las nuevas llamadas. help sigue funcionando.',
    'Les nouveaux appels sont bloqués. help reste disponible.',
    'Neue Tool-Aufrufe sind blockiert. help funktioniert weiterhin.',
  ),
  OK: e('好', '好', 'OK', '확인', 'Aceptar', 'OK', 'OK'),
  'You decide what is on. One click pauses everything.': e(
    '开什么由你决定。一键暂停全部。',
    '開什麼由你決定。一鍵暫停全部。',
    '何をオンにするかはあなた次第。ワンクリックですべて一時停止。',
    '무엇을 켤지는 당신이 정합니다. 한 번에 모두 멈출 수 있습니다.',
    'Tú decides qué está activo. Un clic lo pausa todo.',
    'Vous décidez de ce qui est actif. Un clic suspend tout.',
    'Du entscheidest, was aktiv ist. Ein Klick pausiert alles.',
  ),

  // Get started
  'macOS app + CLI': e('macOS 应用 + CLI', 'macOS 應用程式 + CLI', 'macOS アプリ + CLI', 'macOS 앱 + CLI', 'App de macOS + CLI', 'App macOS + CLI', 'macOS-App + CLI'),

  // Player controls
  Play: e('播放', '播放', '再生', '재생', 'Reproducir', 'Lire', 'Abspielen'),
  Replay: e('重播', '重播', 'もう一度', '다시 재생', 'Repetir', 'Rejouer', 'Wiederholen'),
  Seek: e('跳转', '跳轉', 'シーク', '탐색', 'Buscar', 'Rechercher', 'Suchen'),

  // Image descriptions
  'ReadyRig introduction film': e('ReadyRig 介绍短片', 'ReadyRig 介紹短片', 'ReadyRig 紹介ムービー', 'ReadyRig 소개 영상', 'Película de presentación de ReadyRig', 'Film de présentation de ReadyRig', 'ReadyRig-Einführungsfilm'),
  'The ReadyRig app icon, a vintage ivory Macintosh with an AI chat window on its screen': e(
    'ReadyRig 的应用图标：一台象牙色的复古 Macintosh，屏幕上有 AI 对话窗口',
    'ReadyRig 的應用程式圖示：一台象牙色的復古 Macintosh，螢幕上有 AI 對話視窗',
    'ReadyRig のアプリアイコン。画面に AI チャットウィンドウが映るアイボリーのレトロな Macintosh',
    'ReadyRig 앱 아이콘: 화면에 AI 채팅 창이 떠 있는 아이보리색 빈티지 Macintosh',
    'Icono de ReadyRig: un Macintosh vintage color marfil con una ventana de chat de IA en la pantalla',
    'Icône de l’app ReadyRig : un Macintosh vintage ivoire avec une fenêtre de discussion IA à l’écran',
    'ReadyRig-App-Symbol: ein elfenbeinfarbener Retro-Macintosh mit KI-Chatfenster auf dem Bildschirm',
  ),
  'ReadyRig console, Connection page, with switches for File system, Terminal, Desktop and Chrome browser': e(
    'ReadyRig 控制台“连接”页，带有文件系统、终端、桌面和 Chrome 浏览器的开关',
    'ReadyRig 主控台「連接」頁，帶有檔案系統、終端機、桌面和 Chrome 瀏覽器的開關',
    'ReadyRig コンソールの接続ページ。ファイルシステム、ターミナル、デスクトップ、Chrome ブラウザのスイッチが並ぶ',
    'ReadyRig 콘솔의 연결 페이지: 파일 시스템, 터미널, 데스크톱, Chrome 브라우저 스위치',
    'Consola de ReadyRig, página Conexión, con interruptores para sistema de archivos, terminal, escritorio y navegador Chrome',
    'Console ReadyRig, page Connexion, avec les interrupteurs système de fichiers, terminal, bureau et navigateur Chrome',
    'ReadyRig-Konsole, Seite „Verbindung“, mit Schaltern für Dateisystem, Terminal, Desktop und Chrome-Browser',
  ),
  'The ReadyRig website home page': e('ReadyRig 官网首页', 'ReadyRig 官網首頁', 'ReadyRig 公式サイトのトップページ', 'ReadyRig 웹사이트 홈페이지', 'Página de inicio del sitio de ReadyRig', 'Page d’accueil du site ReadyRig', 'Startseite der ReadyRig-Website'),
  'Captured frame 1': e('截取的画面 1', '擷取的畫面 1', 'キャプチャしたフレーム 1', '캡처한 프레임 1', 'Fotograma capturado 1', 'Image capturée 1', 'Aufgenommenes Bild 1'),
  'Captured frame 2': e('截取的画面 2', '擷取的畫面 2', 'キャプチャしたフレーム 2', '캡처한 프레임 2', 'Fotograma capturado 2', 'Image capturée 2', 'Aufgenommenes Bild 2'),
  'ReadyRig local console, Activity log page': e(
    'ReadyRig 本地控制台“活动日志”页',
    'ReadyRig 本機主控台「活動日誌」頁',
    'ReadyRig ローカルコンソールのアクティビティログページ',
    'ReadyRig 로컬 콘솔의 활동 로그 페이지',
    'Consola local de ReadyRig, página del registro de actividad',
    'Console locale ReadyRig, page du journal d’activité',
    'Lokale ReadyRig-Konsole, Seite „Aktivitätsprotokoll“',
  ),
}
