import type { Locale } from '../locale.ts'

// Translations for the intro film. The film's markup in stage.html is written in English, so English is the source
// and every other locale is listed here; the type forces each entry to cover all of them. Text that is not listed
// (file names, tool names, commands, numbers, times) is the same in every language and stays as it is.
type Entry = Record<Exclude<Locale, 'en'>, string>

const e = (zhCN: string, zhTW: string, ja: string, ko: string, es: string, fr: string, de: string): Entry => ({
  'zh-CN': zhCN,
  'zh-TW': zhTW,
  ja,
  ko,
  es,
  fr,
  de,
})

export const filmStrings: Readonly<Record<string, Entry>> = {
  // Menu bar and chapters
  File: e('文件', '檔案', 'ファイル', '파일', 'Archivo', 'Fichier', 'Datei'),
  Edit: e('编辑', '編輯', '編集', '편집', 'Edición', 'Édition', 'Bearbeiten'),
  View: e('显示', '顯示', '表示', '보기', 'Visualización', 'Présentation', 'Darstellung'),
  Special: e('特别', '特別', '特別', '특별', 'Especial', 'Spécial', 'Spezial'),
  Boot: e('启动', '啟動', '起動', '부팅', 'Inicio', 'Démarrage', 'Start'),
  'The wall': e('隔阂', '隔閡', '壁', '벽', 'El muro', 'Le mur', 'Die Wand'),
  Connect: e('连接', '連接', '接続', '연결', 'Conectar', 'Connexion', 'Verbinden'),
  Work: e('工作', '工作', '作業', '작업', 'Trabajo', 'Travail', 'Arbeit'),
  Screen: e('屏幕', '螢幕', '画面', '화면', 'Pantalla', 'Écran', 'Bildschirm'),
  Logs: e('日志', '日誌', 'ログ', '로그', 'Registros', 'Journaux', 'Protokolle'),
  Console: e('控制台', '主控台', 'コンソール', '콘솔', 'Consola', 'Console', 'Konsole'),
  Activity: e('活动', '活動', 'アクティビティ', '활동', 'Actividad', 'Activité', 'Aktivität'),
  Control: e('控制', '控制', '制御', '제어', 'Control', 'Contrôle', 'Steuerung'),
  'Get started': e('开始使用', '開始使用', 'はじめる', '시작하기', 'Empezar', 'Commencer', 'Los geht’s'),

  // Boot and the wall
  'Remote Agent': e('远程 Agent', '遠端 Agent', 'リモートエージェント', '원격 에이전트', 'Agente remoto', 'Agent distant', 'Remote-Agent'),
  'In the cloud': e('在云端', '在雲端', 'クラウド上', '클라우드에서', 'En la nube', 'Dans le cloud', 'In der Cloud'),
  'Plans the task': e('规划任务', '規劃任務', 'タスクを計画', '작업 계획', 'Planifica la tarea', 'Planifie la tâche', 'Plant die Aufgabe'),
  'Writes the code': e('编写代码', '撰寫程式碼', 'コードを書く', '코드 작성', 'Escribe el código', 'Écrit le code', 'Schreibt den Code'),
  'Reasons it through': e('推理分析', '推理分析', '推論する', '추론', 'Razona el problema', 'Raisonne', 'Denkt es durch'),
  'Your Computer': e('你的电脑', '你的電腦', 'あなたのコンピュータ', '내 컴퓨터', 'Tu ordenador', 'Votre ordinateur', 'Dein Computer'),
  Files: e('文件', '檔案', 'ファイル', '파일', 'Archivos', 'Fichiers', 'Dateien'),
  'out of reach': e('无法访问', '無法存取', 'アクセス不可', '접근 불가', 'fuera de alcance', 'hors de portée', 'außer Reichweite'),
  Terminal: e('终端', '終端機', 'ターミナル', '터미널', 'Terminal', 'Terminal', 'Terminal'),
  'Browser · Desktop': e('浏览器 · 桌面', '瀏覽器 · 桌面', 'ブラウザ · デスクトップ', '브라우저 · 데스크톱', 'Navegador · Escritorio', 'Navigateur · Bureau', 'Browser · Desktop'),
  'Can’t reach “Your Computer”.': e(
    '无法连接“你的电脑”。',
    '無法連接「你的電腦」。',
    '「あなたのコンピュータ」に接続できません。',
    '“내 컴퓨터”에 연결할 수 없습니다.',
    'No se puede acceder a «Tu ordenador».',
    'Impossible d’accéder à « Votre ordinateur ».',
    '„Dein Computer“ ist nicht erreichbar.',
  ),
  'The agent has no hands on this computer.': e(
    'Agent 无法操作这台电脑。',
    'Agent 無法操作這台電腦。',
    'エージェントはこのコンピュータを操作できません。',
    '에이전트는 이 컴퓨터를 조작할 수 없습니다.',
    'El agente no tiene manos en este ordenador.',
    'L’agent n’a pas la main sur cet ordinateur.',
    'Der Agent hat keinen Zugriff auf diesen Computer.',
  ),
  Cancel: e('取消', '取消', 'キャンセル', '취소', 'Cancelar', 'Annuler', 'Abbrechen'),
  '✓ Connected': e('✓ 已连接', '✓ 已連接', '✓ 接続済み', '✓ 연결됨', '✓ Conectado', '✓ Connecté', '✓ Verbunden'),
  'ReadyRig is the bridge.': e('ReadyRig 就是那座桥。', 'ReadyRig 就是那座橋。', 'ReadyRig がその橋渡しです。', 'ReadyRig가 그 다리가 됩니다.', 'ReadyRig es el puente.', 'ReadyRig est le pont.', 'ReadyRig ist die Brücke.'),

  // Connect
  'Remote agent': e('远程 Agent', '遠端 Agent', 'リモートエージェント', '원격 에이전트', 'Agente remoto', 'Agent distant', 'Remote-Agent'),
  'Revocable access': e('可撤销的访问', '可撤銷的存取', '取り消し可能なアクセス', '철회 가능한 액세스', 'Acceso revocable', 'Accès révocable', 'Widerrufbarer Zugriff'),
  Capabilities: e('能力', '功能', '機能', '기능', 'Capacidades', 'Capacités', 'Funktionen'),
  Desktop: e('桌面', '桌面', 'デスクトップ', '데스크톱', 'Escritorio', 'Bureau', 'Desktop'),
  'Public sharing:': e('公网分享：', '公開分享：', '公開共有：', '공개 공유:', 'Compartir públicamente:', 'Partage public :', 'Öffentliches Teilen:'),
  ready: e('就绪', '就緒', '準備完了', '준비됨', 'listo', 'prêt', 'bereit'),
  'temporary link': e('临时链接', '臨時連結', '一時リンク', '임시 링크', 'enlace temporal', 'lien temporaire', 'temporärer Link'),
  'Console · Connection · real screenshot': e(
    '控制台 · 连接 · 真实截图',
    '主控台 · 連接 · 真實截圖',
    'コンソール · 接続 · 実際のスクリーンショット',
    '콘솔 · 연결 · 실제 스크린샷',
    'Consola · Conexión · captura real',
    'Console · Connexion · capture réelle',
    'Konsole · Verbindung · echter Screenshot',
  ),

  // Work
  'Agent chat': e('Agent 对话', 'Agent 對話', 'エージェントチャット', '에이전트 채팅', 'Chat del agente', 'Discussion avec l’agent', 'Agent-Chat'),
  'Read the README and run the tests.': e(
    '读一下 README，然后运行测试。',
    '讀一下 README，然後執行測試。',
    'README を読んで、テストを実行して。',
    'README를 읽고 테스트를 실행해 줘.',
    'Lee el README y ejecuta las pruebas.',
    'Lis le README et lance les tests.',
    'Lies die README und führe die Tests aus.',
  ),
  "On it. I'll use ReadyRig on your computer.": e(
    '好的，我通过 ReadyRig 在你的电脑上操作。',
    '好的，我透過 ReadyRig 在你的電腦上操作。',
    '了解です。ReadyRig であなたのコンピュータを使います。',
    '알겠어요. ReadyRig로 당신의 컴퓨터를 사용할게요.',
    'Entendido. Usaré ReadyRig en tu ordenador.',
    'Je m’en occupe. J’utilise ReadyRig sur votre ordinateur.',
    'Mache ich. Ich nutze ReadyRig auf deinem Computer.',
  ),
  'Done. The tests pass and the README covers install, CLI, security and the console.': e(
    '完成。测试通过，README 涵盖安装、CLI、安全与控制台。',
    '完成。測試通過，README 涵蓋安裝、CLI、安全與主控台。',
    '完了しました。テストは成功し、README にはインストール、CLI、セキュリティ、コンソールが載っています。',
    '완료했어요. 테스트가 통과했고 README는 설치, CLI, 보안, 콘솔을 다룹니다.',
    'Hecho. Las pruebas pasan y el README cubre instalación, CLI, seguridad y consola.',
    'Terminé. Les tests passent et le README couvre l’installation, la CLI, la sécurité et la console.',
    'Fertig. Die Tests bestehen, und die README behandelt Installation, CLI, Sicherheit und Konsole.',
  ),
  'Tool calls': e('工具调用', '工具呼叫', 'ツール呼び出し', '도구 호출', 'Llamadas a herramientas', 'Appels d’outils', 'Tool-Aufrufe'),

  // Screen
  'Chrome · readyrig.getmegaportal.com · real screenshot': e(
    'Chrome · readyrig.getmegaportal.com · 真实截图',
    'Chrome · readyrig.getmegaportal.com · 真實截圖',
    'Chrome · readyrig.getmegaportal.com · 実際のスクリーンショット',
    'Chrome · readyrig.getmegaportal.com · 실제 스크린샷',
    'Chrome · readyrig.getmegaportal.com · captura real',
    'Chrome · readyrig.getmegaportal.com · capture réelle',
    'Chrome · readyrig.getmegaportal.com · echter Screenshot',
  ),
  'Desktop replay': e('桌面回放', '桌面重播', 'デスクトップの再生', '데스크톱 리플레이', 'Reproducción del escritorio', 'Relecture du bureau', 'Desktop-Wiedergabe'),
  'frame by frame': e('逐帧', '逐格', 'コマ送り', '프레임 단위', 'fotograma a fotograma', 'image par image', 'Bild für Bild'),
  Permissions: e('权限', '權限', '権限', '권한', 'Permisos', 'Autorisations', 'Berechtigungen'),
  'Screen Recording': e('屏幕录制', '螢幕錄製', '画面収録', '화면 기록', 'Grabación de pantalla', 'Enregistrement de l’écran', 'Bildschirmaufnahme'),
  Accessibility: e('辅助功能', '輔助使用', 'アクセシビリティ', '손쉬운 사용', 'Accesibilidad', 'Accessibilité', 'Bedienungshilfen'),

  // Logs
  'Activity summary': e('活动概览', '活動概覽', 'アクティビティの概要', '활동 요약', 'Resumen de actividad', 'Résumé de l’activité', 'Aktivitätsübersicht'),
  'Example activity log': e('活动日志示例', '活動日誌範例', 'アクティビティログの例', '활동 로그 예시', 'Registro de actividad de ejemplo', 'Exemple de journal d’activité', 'Beispiel-Aktivitätsprotokoll'),
  'tool calls': e('次工具调用', '次工具呼叫', 'ツール呼び出し', '도구 호출', 'llamadas a herramientas', 'appels d’outils', 'Tool-Aufrufe'),
  succeeded: e('成功', '成功', '成功', '성공', 'correctas', 'réussis', 'erfolgreich'),
  sessions: e('会话', '工作階段', 'セッション', '세션', 'sesiones', 'sessions', 'Sitzungen'),
  clients: e('客户端', '用戶端', 'クライアント', '클라이언트', 'clientes', 'clients', 'Clients'),
  '4 errors and 1 running call. Nothing is hidden.': e(
    '4 个错误、1 个进行中的调用，毫无隐瞒。',
    '4 個錯誤、1 個進行中的呼叫，毫無隱瞞。',
    'エラー4件、実行中1件。隠しごとはありません。',
    '오류 4건, 실행 중 1건. 숨기는 것은 없습니다.',
    '4 errores y 1 llamada en curso. Nada se oculta.',
    '4 erreurs et 1 appel en cours. Rien n’est caché.',
    '4 Fehler und 1 laufender Aufruf. Nichts bleibt verborgen.',
  ),
  'Calls by tool': e('按工具统计调用', '依工具統計呼叫', 'ツール別の呼び出し', '도구별 호출', 'Llamadas por herramienta', 'Appels par outil', 'Aufrufe pro Tool'),
  'Calls per day': e('每日调用', '每日呼叫', '日別の呼び出し', '일별 호출', 'Llamadas por día', 'Appels par jour', 'Aufrufe pro Tag'),
  'Sep 30': e('9月30日', '9月30日', '9月30日', '9월 30일', '30 sep', '30 sept.', '30. Sep'),
  'Oct 1': e('10月1日', '10月1日', '10月1日', '10월 1일', '1 oct', '1 oct.', '1. Okt'),
  'Oct 2': e('10月2日', '10月2日', '10月2日', '10월 2일', '2 oct', '2 oct.', '2. Okt'),
  'solid: local tools': e('实心：本地工具', '實心：本機工具', '塗りつぶし：ローカルツール', '채움: 로컬 도구', 'sólido: herramientas locales', 'plein : outils locaux', 'gefüllt: lokale Tools'),
  'hatched: Chrome tools': e('斜纹：Chrome 工具', '斜紋：Chrome 工具', '斜線：Chrome ツール', '빗금: Chrome 도구', 'rayado: herramientas de Chrome', 'hachuré : outils Chrome', 'schraffiert: Chrome-Tools'),

  // Console
  'ReadyRig console · Activity · real screenshot': e(
    'ReadyRig 控制台 · 活动 · 真实截图',
    'ReadyRig 主控台 · 活動 · 真實截圖',
    'ReadyRig コンソール · アクティビティ · 実際のスクリーンショット',
    'ReadyRig 콘솔 · 활동 · 실제 스크린샷',
    'Consola de ReadyRig · Actividad · captura real',
    'Console ReadyRig · Activité · capture réelle',
    'ReadyRig-Konsole · Aktivität · echter Screenshot',
  ),
  'The console': e('控制台', '主控台', 'コンソール', '콘솔', 'La consola', 'La console', 'Die Konsole'),
  'Calls, running, time': e('调用、进行中、耗时', '呼叫、進行中、耗時', '呼び出し・実行中・所要時間', '호출, 실행 중, 소요 시간', 'Llamadas, en curso, tiempo', 'Appels, en cours, durée', 'Aufrufe, laufend, Zeit'),
  'Filter by tool kind': e('按工具类型筛选', '依工具類型篩選', 'ツールの種類で絞り込み', '도구 종류별 필터', 'Filtrar por tipo de herramienta', 'Filtrer par type d’outil', 'Nach Tool-Art filtern'),
  'Search args and errors': e('搜索参数与错误', '搜尋參數與錯誤', '引数とエラーを検索', '인자와 오류 검색', 'Buscar argumentos y errores', 'Rechercher arguments et erreurs', 'Argumente und Fehler durchsuchen'),
  'Pause in one click': e('一键暂停', '一鍵暫停', 'ワンクリックで一時停止', '한 번에 일시중지', 'Pausa con un clic', 'Pause en un clic', 'Pause mit einem Klick'),
  'Export as NDJSON': e('导出为 NDJSON', '匯出為 NDJSON', 'NDJSON で書き出し', 'NDJSON으로 내보내기', 'Exportar como NDJSON', 'Exporter en NDJSON', 'Als NDJSON exportieren'),

  // Activity
  'Activity · example log · times in UTC': e(
    '活动 · 示例日志 · 时间为 UTC',
    '活動 · 範例日誌 · 時間為 UTC',
    'アクティビティ · ログの例 · 時刻は UTC',
    '활동 · 예시 로그 · 시간은 UTC',
    'Actividad · registro de ejemplo · horas en UTC',
    'Activité · exemple de journal · heures en UTC',
    'Aktivität · Beispielprotokoll · Zeiten in UTC',
  ),
  Time: e('时间', '時間', '時刻', '시간', 'Hora', 'Heure', 'Zeit'),
  Tool: e('工具', '工具', 'ツール', '도구', 'Herramienta', 'Outil', 'Tool'),
  Client: e('客户端', '用戶端', 'クライアント', '클라이언트', 'Cliente', 'Client', 'Client'),
  Took: e('耗时', '耗時', '所要時間', '소요', 'Duración', 'Durée', 'Dauer'),
  Result: e('结果', '結果', '結果', '결과', 'Resultado', 'Résultat', 'Ergebnis'),
  '◔ running': e('◔ 进行中', '◔ 進行中', '◔ 実行中', '◔ 실행 중', '◔ en curso', '◔ en cours', '◔ läuft'),
  '✓ success': e('✓ 成功', '✓ 成功', '✓ 成功', '✓ 성공', '✓ correcto', '✓ succès', '✓ Erfolg'),
  '✕ error': e('✕ 错误', '✕ 錯誤', '✕ エラー', '✕ 오류', '✕ error', '✕ erreur', '✕ Fehler'),

  // Control
  'Control panel': e('控制面板', '控制面板', 'コントロールパネル', '제어판', 'Panel de control', 'Panneau de contrôle', 'Bedienfeld'),
  'approved folders only': e('仅限已批准的文件夹', '僅限已核准的資料夾', '承認済みフォルダのみ', '승인된 폴더만', 'solo carpetas aprobadas', 'dossiers approuvés uniquement', 'nur freigegebene Ordner'),
  'off until you say so': e('你开启前保持关闭', '你開啟前保持關閉', 'あなたがオンにするまでオフ', '직접 켜기 전까지 꺼짐', 'desactivado hasta que lo indiques', 'désactivé tant que vous ne l’autorisez pas', 'aus, bis du es erlaubst'),
  'needs macOS permission': e('需要 macOS 授权', '需要 macOS 授權', 'macOS の許可が必要', 'macOS 권한 필요', 'requiere permiso de macOS', 'nécessite l’autorisation macOS', 'benötigt macOS-Freigabe'),
  'Full Access': e('完全访问', '完整存取', 'フルアクセス', '전체 접근', 'Acceso total', 'Accès complet', 'Vollzugriff'),
  'per session only': e('仅限本次会话', '僅限本次工作階段', 'このセッションのみ', '세션 동안만', 'solo por sesión', 'par session uniquement', 'nur pro Sitzung'),
  'Log, secrets redacted': e('日志，密钥已隐去', '日誌，密鑰已隱去', 'ログ（秘密情報は伏せ字）', '로그, 비밀 정보 가림', 'Registro, secretos ocultos', 'Journal, secrets masqués', 'Protokoll, Geheimnisse geschwärzt'),
  'stays on your computer': e('留在你的电脑上', '留在你的電腦上', 'あなたのコンピュータに残ります', '당신의 컴퓨터에 남습니다', 'se queda en tu ordenador', 'reste sur votre ordinateur', 'bleibt auf deinem Computer'),
  Pause: e('暂停', '暫停', '一時停止', '일시중지', 'Pausa', 'Pause', 'Pause'),
  'Paused.': e('已暂停。', '已暫停。', '一時停止中。', '일시중지됨.', 'En pausa.', 'En pause.', 'Pausiert.'),
  'New tool calls are blocked. Help still works.': e(
    '新的工具调用已被阻止，help 仍可使用。',
    '新的工具呼叫已被阻擋，help 仍可使用。',
    '新しいツール呼び出しはブロックされます。help は引き続き使えます。',
    '새 도구 호출은 차단됩니다. help는 계속 작동합니다.',
    'Se bloquean las nuevas llamadas. help sigue funcionando.',
    'Les nouveaux appels sont bloqués. help reste disponible.',
    'Neue Tool-Aufrufe sind blockiert. help funktioniert weiterhin.',
  ),
  OK: e('好', '好', 'OK', '확인', 'Aceptar', 'OK', 'OK'),

  // Get started
  'macOS app + CLI': e('macOS 应用 + CLI', 'macOS 應用程式 + CLI', 'macOS アプリ + CLI', 'macOS 앱 + CLI', 'App de macOS + CLI', 'App macOS + CLI', 'macOS-App + CLI'),

  // Captions
  'Your computer, ready for a remote AI agent.': e(
    '你的电脑，随时为远程 AI Agent 就绪。',
    '你的電腦，隨時為遠端 AI Agent 就緒。',
    'あなたのコンピュータを、リモート AI エージェントのために。',
    '당신의 컴퓨터를 원격 AI 에이전트에게 열어 두세요.',
    'Tu ordenador, listo para un agente de IA remoto.',
    'Votre ordinateur, prêt pour un agent IA distant.',
    'Dein Computer, bereit für einen Remote-KI-Agenten.',
  ),
  'Remote AI agents can plan and write code, but can’t reach your computer.': e(
    '远程 AI Agent 能规划、写代码，却够不到你的电脑。',
    '遠端 AI Agent 能規劃、寫程式，卻碰不到你的電腦。',
    'リモート AI エージェントは計画もコード作成もできますが、あなたのコンピュータには手が届きません。',
    '원격 AI 에이전트는 계획하고 코드를 쓸 수 있지만, 당신의 컴퓨터에는 닿지 못합니다.',
    'Los agentes de IA remotos pueden planificar y escribir código, pero no llegan a tu ordenador.',
    'Les agents IA distants savent planifier et écrire du code, mais ne peuvent pas atteindre votre ordinateur.',
    'Remote-KI-Agenten können planen und Code schreiben, erreichen aber deinen Computer nicht.',
  ),
  'Through a cloud connection, your remote AI agent uses the tools you enable.': e(
    '通过云端连接，远程 AI Agent 使用你开启的工具。',
    '透過雲端連接，遠端 AI Agent 使用你開啟的工具。',
    'クラウド接続を通じて、リモート AI エージェントはあなたが有効にしたツールを使います。',
    '클라우드 연결을 통해 원격 AI 에이전트가 당신이 켠 도구를 사용합니다.',
    'Con una conexión en la nube, tu agente de IA remoto usa las herramientas que actives.',
    'Via une connexion cloud, votre agent IA distant utilise les outils que vous activez.',
    'Über eine Cloud-Verbindung nutzt dein Remote-KI-Agent die Tools, die du aktivierst.',
  ),
  'Files, terminal, desktop, browser: you choose what is available.': e(
    '文件、终端、桌面、浏览器：开放什么由你选择。',
    '檔案、終端機、桌面、瀏覽器：開放什麼由你選擇。',
    'ファイル、ターミナル、デスクトップ、ブラウザ。何を使えるかはあなたが選びます。',
    '파일, 터미널, 데스크톱, 브라우저: 무엇을 열지는 당신이 고릅니다.',
    'Archivos, terminal, escritorio, navegador: tú eliges qué está disponible.',
    'Fichiers, terminal, bureau, navigateur : vous choisissez ce qui est disponible.',
    'Dateien, Terminal, Desktop, Browser: Du wählst, was verfügbar ist.',
  ),
  'Link several computers to one account, and the agent can pick the right one.': e(
    '把多台电脑绑定到同一账号，Agent 就能选择合适的那台。',
    '把多台電腦綁定到同一帳號，Agent 就能選擇合適的那台。',
    '複数のコンピュータを1つのアカウントにひも付ければ、エージェントが適切な1台を選べます。',
    '여러 컴퓨터를 한 계정에 연결하면 에이전트가 알맞은 컴퓨터를 고를 수 있습니다.',
    'Vincula varios ordenadores a una cuenta y el agente podrá elegir el adecuado.',
    'Liez plusieurs ordinateurs à un compte, et l’agent choisit le bon.',
    'Verknüpfe mehrere Computer mit einem Konto, und der Agent wählt den passenden.',
  ),
  'Give it a task in plain words. It reads files, runs commands and reports back.': e(
    '用平常的话交代任务。它读取文件、运行命令，再汇报结果。',
    '用平常的話交代任務。它讀取檔案、執行指令，再回報結果。',
    'ふつうの言葉でタスクを渡すだけ。ファイルを読み、コマンドを実行し、結果を報告します。',
    '평소 말투로 작업을 맡기세요. 파일을 읽고 명령을 실행한 뒤 결과를 보고합니다.',
    'Dale una tarea con tus palabras. Lee archivos, ejecuta comandos e informa del resultado.',
    'Confiez-lui une tâche simplement. Il lit des fichiers, lance des commandes et vous rend compte.',
    'Gib ihm eine Aufgabe in einfachen Worten. Er liest Dateien, führt Befehle aus und meldet das Ergebnis.',
  ),
  'Grant Screen Recording and Accessibility, and the agent can see the screen and click.': e(
    '授予“屏幕录制”和“辅助功能”权限后，Agent 就能看到屏幕并点击。',
    '授予「螢幕錄製」與「輔助使用」權限後，Agent 就能看到螢幕並點擊。',
    '画面収録とアクセシビリティを許可すると、エージェントは画面を見てクリックできます。',
    '화면 기록과 손쉬운 사용 권한을 허용하면 에이전트가 화면을 보고 클릭할 수 있습니다.',
    'Concede Grabación de pantalla y Accesibilidad, y el agente podrá ver la pantalla y hacer clic.',
    'Accordez Enregistrement de l’écran et Accessibilité, et l’agent voit l’écran et peut cliquer.',
    'Erlaube Bildschirmaufnahme und Bedienungshilfen, und der Agent kann den Bildschirm sehen und klicken.',
  ),
  'Desktop replay lets you review its actions, frame by frame.': e(
    '桌面回放让你逐帧回看它的操作。',
    '桌面重播讓你逐格回看它的操作。',
    'デスクトップの再生で、操作をコマ送りで振り返れます。',
    '데스크톱 리플레이로 에이전트의 동작을 프레임 단위로 되돌아볼 수 있습니다.',
    'La reproducción del escritorio te permite revisar sus acciones fotograma a fotograma.',
    'La relecture du bureau permet de revoir ses actions image par image.',
    'Mit der Desktop-Wiedergabe prüfst du seine Aktionen Bild für Bild.',
  ),
  'Every tool call is recorded in a local database on your computer.': e(
    '每一次工具调用，都记录在你电脑上的本地数据库中。',
    '每一次工具呼叫，都記錄在你電腦上的本機資料庫中。',
    'すべてのツール呼び出しは、あなたのコンピュータ上のローカルデータベースに記録されます。',
    '모든 도구 호출은 당신의 컴퓨터의 로컬 데이터베이스에 기록됩니다.',
    'Cada llamada a una herramienta se registra en una base de datos local de tu ordenador.',
    'Chaque appel d’outil est enregistré dans une base de données locale sur votre ordinateur.',
    'Jeder Tool-Aufruf wird in einer lokalen Datenbank auf deinem Computer gespeichert.',
  ),
  'See what succeeded, what failed and what is still running.': e(
    '哪些成功、哪些失败、哪些仍在进行，一目了然。',
    '哪些成功、哪些失敗、哪些仍在進行，一目了然。',
    '成功したもの、失敗したもの、実行中のものがひと目でわかります。',
    '성공한 호출, 실패한 호출, 진행 중인 호출을 한눈에 볼 수 있습니다.',
    'Ve qué salió bien, qué falló y qué sigue en curso.',
    'Voyez ce qui a réussi, ce qui a échoué et ce qui est encore en cours.',
    'Sieh, was erfolgreich war, was fehlgeschlagen ist und was noch läuft.',
  ),
  'Follow calls in real time in the desktop app or a browser console.': e(
    '在桌面 App 或浏览器控制台中实时跟踪每次调用。',
    '在桌面 App 或瀏覽器主控台中即時追蹤每次呼叫。',
    'デスクトップアプリまたはブラウザのコンソールで、呼び出しをリアルタイムに追えます。',
    '데스크톱 앱이나 브라우저 콘솔에서 호출을 실시간으로 따라가세요.',
    'Sigue las llamadas en tiempo real en la app de escritorio o en una consola del navegador.',
    'Suivez les appels en direct dans l’app de bureau ou une console de navigateur.',
    'Verfolge Aufrufe in Echtzeit in der Desktop-App oder einer Browser-Konsole.',
  ),
  'Filter by tool, search for errors, export your logs.': e(
    '按工具筛选、搜索错误、导出日志。',
    '依工具篩選、搜尋錯誤、匯出日誌。',
    'ツールで絞り込み、エラーを検索し、ログを書き出せます。',
    '도구별로 필터링하고, 오류를 검색하고, 로그를 내보내세요.',
    'Filtra por herramienta, busca errores y exporta tus registros.',
    'Filtrez par outil, cherchez les erreurs, exportez vos journaux.',
    'Nach Tool filtern, nach Fehlern suchen, Protokolle exportieren.',
  ),
  'Each record shows the tool, duration and result.': e(
    '每条记录都显示工具、耗时和结果。',
    '每筆記錄都顯示工具、耗時與結果。',
    '各記録には、ツール・所要時間・結果が表示されます。',
    '각 기록에는 도구, 소요 시간, 결과가 표시됩니다.',
    'Cada registro muestra la herramienta, la duración y el resultado.',
    'Chaque entrée indique l’outil, la durée et le résultat.',
    'Jeder Eintrag zeigt Tool, Dauer und Ergebnis.',
  ),
  'Failed calls stay in the log, so you can investigate before trying again.': e(
    '失败的调用会留在日志里，重试前可以先排查。',
    '失敗的呼叫會留在日誌中，重試前可以先排查。',
    '失敗した呼び出しもログに残るので、再試行する前に原因を調べられます。',
    '실패한 호출도 로그에 남아, 다시 시도하기 전에 원인을 살펴볼 수 있습니다.',
    'Las llamadas fallidas permanecen en el registro, para que investigues antes de reintentar.',
    'Les appels échoués restent dans le journal : vous pouvez enquêter avant de réessayer.',
    'Fehlgeschlagene Aufrufe bleiben im Protokoll, damit du sie vor einem neuen Versuch prüfen kannst.',
  ),
  'You decide which capabilities are on.': e(
    '开启哪些能力，由你决定。',
    '開啟哪些能力，由你決定。',
    'どの機能をオンにするかは、あなたが決めます。',
    '어떤 기능을 켤지는 당신이 정합니다.',
    'Tú decides qué capacidades están activas.',
    'Vous décidez des capacités activées.',
    'Du entscheidest, welche Funktionen aktiv sind.',
  ),
  'One click pauses access and blocks new tool calls.': e(
    '一键暂停访问，并阻止新的工具调用。',
    '一鍵暫停存取，並阻擋新的工具呼叫。',
    'ワンクリックでアクセスを一時停止し、新しいツール呼び出しをブロックします。',
    '한 번의 클릭으로 접근을 일시중지하고 새 도구 호출을 차단합니다.',
    'Un clic pausa el acceso y bloquea las nuevas llamadas a herramientas.',
    'Un clic suspend l’accès et bloque les nouveaux appels d’outils.',
    'Ein Klick pausiert den Zugriff und blockiert neue Tool-Aufrufe.',
  ),
  'Turn your computer into a workspace for your remote AI agent.': e(
    '把你的电脑，变成远程 AI Agent 的工作空间。',
    '把你的電腦，變成遠端 AI Agent 的工作空間。',
    'あなたのコンピュータを、リモート AI エージェントの作業場に。',
    '당신의 컴퓨터를 원격 AI 에이전트의 작업 공간으로 만드세요.',
    'Convierte tu ordenador en un espacio de trabajo para tu agente de IA remoto.',
    'Faites de votre ordinateur un espace de travail pour votre agent IA distant.',
    'Mach deinen Computer zum Arbeitsplatz für deinen Remote-KI-Agenten.',
  ),

  // Player controls
  Play: e('播放', '播放', '再生', '재생', 'Reproducir', 'Lire', 'Abspielen'),
  Replay: e('重播', '重播', 'もう一度', '다시 재생', 'Repetir', 'Rejouer', 'Wiederholen'),
  Seek: e('跳转', '跳轉', 'シーク', '탐색', 'Buscar', 'Rechercher', 'Suchen'),

  // Image descriptions
  'ReadyRig introduction film': e('ReadyRig 介绍短片', 'ReadyRig 介紹短片', 'ReadyRig 紹介ムービー', 'ReadyRig 소개 영상', 'Película de presentación de ReadyRig', 'Film de présentation de ReadyRig', 'ReadyRig-Einführungsfilm'),
  'The ReadyRig app icon, a vintage ivory Macintosh with an AI chat window on its screen': e(
    'ReadyRig 的应用图标：一台象牙色的复古 Macintosh，屏幕上有 AI 对话窗口',
    'ReadyRig 的應用程式圖示：一台象牙色的復古 Macintosh，螢幕上有 AI 對話視窗',
    'ReadyRig のアプリアイコン。画面に AI チャットウィンドウが映るアイボリーのレトロな Macintosh',
    'ReadyRig 앱 아이콘: 화면에 AI 채팅 창이 떠 있는 아이보리색 빈티지 Macintosh',
    'Icono de ReadyRig: un Macintosh vintage color marfil con una ventana de chat de IA en la pantalla',
    'Icône de l’app ReadyRig : un Macintosh vintage ivoire avec une fenêtre de discussion IA à l’écran',
    'ReadyRig-App-Symbol: ein elfenbeinfarbener Retro-Macintosh mit KI-Chatfenster auf dem Bildschirm',
  ),
  'ReadyRig console, Connection page, with switches for File system, Terminal, Desktop and Chrome browser': e(
    'ReadyRig 控制台“连接”页，带有文件系统、终端、桌面和 Chrome 浏览器的开关',
    'ReadyRig 主控台「連接」頁，帶有檔案系統、終端機、桌面和 Chrome 瀏覽器的開關',
    'ReadyRig コンソールの接続ページ。ファイルシステム、ターミナル、デスクトップ、Chrome ブラウザのスイッチが並ぶ',
    'ReadyRig 콘솔의 연결 페이지: 파일 시스템, 터미널, 데스크톱, Chrome 브라우저 스위치',
    'Consola de ReadyRig, página Conexión, con interruptores para sistema de archivos, terminal, escritorio y navegador Chrome',
    'Console ReadyRig, page Connexion, avec les interrupteurs système de fichiers, terminal, bureau et navigateur Chrome',
    'ReadyRig-Konsole, Seite „Verbindung“, mit Schaltern für Dateisystem, Terminal, Desktop und Chrome-Browser',
  ),
  'The ReadyRig website home page': e('ReadyRig 官网首页', 'ReadyRig 官網首頁', 'ReadyRig 公式サイトのトップページ', 'ReadyRig 웹사이트 홈페이지', 'Página de inicio del sitio de ReadyRig', 'Page d’accueil du site ReadyRig', 'Startseite der ReadyRig-Website'),
  'Captured frame 1': e('截取的画面 1', '擷取的畫面 1', 'キャプチャしたフレーム 1', '캡처한 프레임 1', 'Fotograma capturado 1', 'Image capturée 1', 'Aufgenommenes Bild 1'),
  'Captured frame 2': e('截取的画面 2', '擷取的畫面 2', 'キャプチャしたフレーム 2', '캡처한 프레임 2', 'Fotograma capturado 2', 'Image capturée 2', 'Aufgenommenes Bild 2'),
  'ReadyRig local console, Activity log page': e(
    'ReadyRig 本地控制台“活动日志”页',
    'ReadyRig 本機主控台「活動日誌」頁',
    'ReadyRig ローカルコンソールのアクティビティログページ',
    'ReadyRig 로컬 콘솔의 활동 로그 페이지',
    'Consola local de ReadyRig, página del registro de actividad',
    'Console locale ReadyRig, page du journal d’activité',
    'Lokale ReadyRig-Konsole, Seite „Aktivitätsprotokoll“',
  ),
}
